### ISSUE TITLE
Improve keyboard focus with distinct styling

### ISSUE THREAD

**Issue by EHLOVader** [EHLOVader/ehlovader.github.io#8]
Make the keyboard focus more of an inverted block and outline the link

Expand that outline also so the text is still readable.
Something like this

```scss
		&:focus {
			outline-offset: -3px;
			padding: 6px;
			margin: -6px;
			outline: dotted;
			background: #222;
			color: #fff;
		}
```
